export const particleIds = {
    mobflame_emitter:'minecraft:mobflame_emitter',
    // test_beziercurve:'minecraft:test_beziercurve',
    // test_bounce:'minecraft:test_bounce',
    // test_catmullromcurve:'minecraft:test_catmullromcurve',
    // test_colorcurve:'minecraft:test_colorcurve',
    // test_combocurve:'minecraft:test_combocurve',
    // test_highrestitution:'minecraft:test_highrestitution',
    // test_linearcurve:'minecraft:test_linearcurve',
    // test_mule:'minecraft:test_mule',
    // test_smoke_puff:'minecraft:test_smoke_puff',
    // test_sphere:'minecraft:test_sphere',
    // test_spiral:'minecraft:test_spiral',
    // test_watertest:'minecraft:test_watertest',
    // test_flipbook:'minecraft:test_flipbook',
    // test_vertexrandom:'minecraft:test_vertexrandom',
    balloon_gas_particle:'minecraft:balloon_gas_particle',
    mobspell_emitter:'minecraft:mobspell_emitter',
    basic_crit_particle:'minecraft:basic_crit_particle',
    portal_directional:'minecraft:portal_directional',
    bubble_column_down_particle:'minecraft:bubble_column_down_particle',
    portal_east_west:'minecraft:portal_east_west',
    portal_north_south:'minecraft:portal_north_south',
    bubble_column_up_particle:'minecraft:bubble_column_up_particle',
    crit_emitter:'minecraft:crit_emitter',
    splash_spell_emitter:'minecraft:splash_spell_emitter',
    end_chest:'minecraft:end_chest',
    totem_particle:'minecraft:totem_particle',
    evocation_fang_particle:'minecraft:evocation_fang_particle',
    water_splash_particle:'minecraft:water_splash_particle',
    evoker_spell:'minecraft:evoker_spell',
    water_wake_particle:'minecraft:water_wake_particle',
    magnesium_salts_emitter:'minecraft:magnesium_salts_emitter',
    wither_boss_invulnerable:'minecraft:wither_boss_invulnerable',
    mob_portal:'minecraft:mob_portal',
};
Object.freeze(particleIds);